apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: web
          image: flvasques/convercao-temperatura:v1
          ports:
          - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: servicoweb
spec:
  selector:
    app: front
  ports:  
    - protocol: TCP
      port: 8080
      nodePort: 30000
  type: NodePort
